#ifndef CONSTANTS_H
#define CONSTANTS_H

// MISCELLANEOUS
#define FPS 120
#define MAP_SIZE 750
#define INFINITE_LOOP_GUARD 100
#define TITLE_CARD "welcome to fuck you"
#define HURTBOX_TELEGRAPH_ALPHA 0.3
#define WAVE_INTERMISSION 1.2
#define INVALID_KEY -1
#define INVALID_INDEX -1

// CAMERA
#define CAMERA_ACCELERATION_COE 4000
#define CAMERA_RESISTANCE_COE 3
#define DEFAULT_CAMERA_ZOOM 1
#define MAX_CAMERA_ZOOM 1.3
#define CAMERA_ZOOM_TAU 20
#define MAXIMUM_SLOW 0.1

// PLAYER
#define PLAYER_MAX_HEALTH 999
#define PLAYER_RADIUS 4
#define PLAYER_RESISTANCE_COE 8
#define PLAYER_ACCELERATION_COE 6000
#define PLAYER_CROUCH_RESISTANCE_COE 28
#define PLAYER_DASH_RADIUS 14
#define PLAYER_DASH_DAMAGE 1

#define SLOW_DURATION 1

#define DASH_DURATION 0.2
#define DASH_COOLDOWN 0.6
#define DASH_RESISTANCE_COE 8
#define DASH_ACCELERATION_COE 15
#define DASH_BOUNCINESS 1.0
#define BOUNCE_EXTENSION_COE 2
#define NOT_DASHING_BOUNCE_COE 0.5
#define DASH_ZOOM_COE 3
#define DASH_ZOOM_DECAY 2
#define DASH_STEERING_COE 0.2
#define INVINCIBILITY_DURATION 1
#define HITBOX_COLLISION_LAUNCH_COE 6000

// ENEMIES
#define ENEMY_INVINCIBLE_DURATION 0.05
#define MAX_ENEMIES 64
#define MAX_HURTBOXES 1000

// CHASERS
#define CHASER_RADIUS 14
#define CHASER_HEALTH 1
#define CHASER_KNOCKBACK_COEFFECIENT 1
#define CHASER_STALKING_ORBITAL_VELOCITY 1.5
#define CHASER_STALKING_ACCELERATION 2500
#define CHASER_STALKING_RESISTANCE 4
#define CHASER_STALKING_ORBITAL_UPPER_RADIUS 200
#define CHASER_STALKING_ORBITAL_LOWER_RADIUS 300
#define CHASER_FLANKING_ORBITAL_VELOCITY 4
#define CHASER_FLANKING_ACCELERATION 10000
#define CHASER_FLANKING_RESISTANCE 18
#define CHASER_FLANKING_ORBITAL_RADIUS 50
#define CHASER_ATTACKING_RADIUS 150
#define CHASER_ATTACKING_ACCELERATION 4000
#define CHASER_ATTACKING_RESISTANCE 4
#define CHASER_SCATTERING_ACCELERATION 2500
#define CHASER_SCATTERING_RESISTANCE 4
#define CHASER_ATTACK_COOLDOWN 3
#define CHASER_DASH_DURATION 0.2
#define CHASER_DASH_SPEED 1000

// BOMBERS
#define BOMBER_HEALTH 100
#define BOMBER_RADIUS 20
#define BOMBER_KNOCKBACK_COEFFICIENT 2
#define BOMBER_AGGRO_CHECK_COOLDOWN 1
#define BOMBER_CHASE_COEFFICIENT 10
#define BOMBER_AGGRO_RANGE 250
#define BOMBER_AGRRO_COEFFICIENT 5
#define BOMBER_STALKING_RANGE 500
#define BOMBER_STALKING_ACCEL 600
#define BOMBER_STALKING_RESISTANCE 3
#define BOMBER_CHASING_ACCEL 8000
#define BOMBER_CHASING_RESISTANCE 12
#define BOMBER_ATTACKING_FUSE_THRESHOLD 1
#define BOMBER_ATTACKING_RADIUS 100
#define BOMBER_ATTACKING_RESISTANCE 3
#define BOMBER_FUSE_DURATION 4
#define BOMBER_EXPLOSION_RADIUS 400
#define BOMBER_EXPLOSION_DURATION 0.2
#define BOMBER_CHAIN_FUSE_DURATION 0.2
#define BOMBER_SPAWN_DISTANCE 500
#define BOMBER_EXPLOSION_DAMAGE 2

#define CHASER_CHASING_BOMBER_SAFETY_RADIUS (BOMBER_EXPLOSION_RADIUS / 2)
#define CHASER_ATTACKING_BOMBER_SAFETY_RADIUS (BOMBER_EXPLOSION_RADIUS + 50)

// LASERS
#define LASER_HEALTH 2
#define LASER_RADIUS 18
#define LASER_KNOCKBACK_COEFFICIENT 0.5
#define LASER_STALKING_FAST_ACCELERATION 500
#define LASER_STALKING_MEDIUM_ACCELERATION 300
#define LASER_STALKING_SLOW_ACCELERATION 200
#define LASER_STALKING_RESISTANCE 1
#define LASER_RUN_FROM_PLAYER_RADIUS 300
#define LASER_LOWER_OUTER_SPAWN_BOUNDS 400
#define LASER_PLAYER_DISTANCE_SPAWN_BOUNDS 500
#define LASER_ATTACK_COOLDOWN 3
#define LASER_ATTACK_RADIUS 20
#define LASER_WAITING_RESISTANCE 5
#define LASER_FIRE_DELAY 0.5
#define LASER_FIRE_DELAY_BUFFER 0.1
#define LASER_AIM_DURATION 2
#define LASER_AIM_ACCELERATION 13000
#define LASER_AIM_RESISTANCE 10
#define LASER_AIM_LOCK 10
#define LASER_FIRE_ACCELERATION 1000
#define LASER_FIRE_RESISTANCE 15
#define LASER_FIRE_DURATION 3
#define ARBITRARY_LARGE_NUMBER 999

// DRONES
#define MAX_DRONES 8
#define DRONE_HEALTH 1
#define DRONE_RADIUS 8
#define DRONE_KNOCKBACK_COEFFICIENT 1
#define DRONE_STALKING_DURATION 8 // TUNE 8
#define DRONE_STALKING_PLAYER_REPULSION_COEFFICIENT 6
#define DRONE_STALKING_PLAYER_REPULSION_DISTANCE 100
#define DRONE_POSITIONING_LOCK_THRESHOLD 10
#define DRONE_POSITIONING_UNLOCK_THRESHOLD 25
#define DRONE_POSITIONING_ACCELERATION 12000
#define DRONE_ORBIT_DURATION 1 // TUNE 1
#define DRONE_BASE_ORBITING_RADIUS 200
#define DRONE_MIN_RADIUS 150
#define DRONE_MAX_RADIUS 600
#define DRONE_MAX_ANGULAR_VELOCITY 12
#define DRONE_DUO_MAX_ANGULAR_VELOCITY PI / 2
#define DRONE_CENTRE_TRANSLATIONAL_ACCELERATION 180
#define DRONE_CENTRE_TRANSLATIONAL_RESISTANCE 1
#define DRONE_CENTRE_TRANSLATION_BUFFER 100
#define DRONE_BASE_VECTOR_MODULUS_INCREASE_RATE 75
#define DRONE_ORBITINGING_RADIUS 300
#define DRONE_TRANSLATE_RADIUS 450
#define DRONE_BASE_BARRAGING_RADIUS 450
#define DRONE_BASE_BARRAGING_INTERVAL_MULTIPLIER 1
#define DRONE_PASSIVE_LASER_COOLDOWN 0.005
#define DRONE_PASSIVE_LASER_DURATION 0.15
#define DRONE_ORBITAL_ACCELERATION 2 * PI
#define DRONE_DUO_ORBITAL_ACCELERATION PI / 4
#define DRONE_ACTIVE_LASER_COOLDOWN 1
#define DRONE_ACTIVE_LASER_TELEGRAPH 0.8
#define DRONE_ACTIVE_LASER_DURATION 0.5
#define DRONE_ACTIVE_LASER_MINIMUM_ANGLE_DIFFERENCE 100
#define DRONE_ATTACK_INTERVAL_DECREASE 0.9
#define DRONE_MAX_ATTACK_INTERVAL_MULTIPLIER 1
#define DRONE_MIN_ATTACK_INTERVAL_MULTIPLIER 0.2
#define DRONE_MIN_ATTACK_DURATION 3
#define DRONE_RADIUS_INCREASE_PER_NOT_DRONE 50
#define DRONE_RADIUS_DECREASE_PER_DRONE 30
#define DRONE_ATTACK_INTERVAL_INCREASE_PER_NOT_DRONE 0.1
#define DRONE_ATTACK_INTERVAL_DECREASE_PER_DRONE 0.04
#define DRONE_MINIMUM_ATTACK_INTERVAL_MULTIPLIER 0.7
#define DRONE_MAXIMUM_ATTACK_INTERVAL_MULTIPLIER 1.5
#define DRONE_BIG_LASER_THICKNESS 10
#define DRONE_BIG_LASER_TELEGRAPH_DURATION 2
#define DRONE_BIG_LASER_ANGULAR_ACCELERATION 1.25 // TUNE
#define DRONE_BIG_LASER_MAX_ANGULAR_VELOCITY PI / 3 // TUNE
#define DRONE_BIG_LASER_ANGULAR_RESISTANCE 0.8
#define DRONE_BIG_LASER_TIMER 6
#define DRONE_GIVE_UP_RESISTANCE 2
#define DRONE_EXPLOSION_RADIUS 30
#define DRONE_EXPLODE_TELEGRAPH 0.4

// CHARGERS
#define CHARGER_HEALTH 69420
#define CHARGER_RADIUS 100
#define CHARGER_WEAKPOINT_HEALTH 1
#define CHARGER_WEAKPOINT_RADIUS 20 
#define CHARGER_KNOCKBACK_COEFFECIENT 0
#define CHARGER_PLAYER_MIN_SPAWN_DISTANCE 200
#define CHARGER_WEAKPOINT_COUNT 3
#define CHARGER_WEAKPOINT_SEPERATION PI / 6
#define CHARGER_WEAKPOINT_INVINCIBILITY_DURATION 5
#define CHARGER_ENTER_STOMP_RANGE 200
#define CHARGER_STOMP_RADIUS 250
#define CHARGER_STOMP_TELEGRAPH 1
#define CHARGER_STOMP_DURATION 0.1
#define CHARGER_STOMPING_DURATION 1.3
#define CHARGER_STALKING_DURATION 3 //TUNE
#define CHARGER_STALKING_ACCELERATION 100
#define CHARGER_STALKING_RESISTANCE 1
#define CHARGER_STALKING_RANGE 500
#define CHARGER_POSITIONING_DURATION 3 //TUNE
#define CHARGER_CHARGING_ACCELERATION 2200
#define CHARGER_CHARGING_RESISTANCE 1
#define CHARGER_MAX_BOUNCES 1
#define CHARGER_MAX_BOUNCE_INCREASE 2
#define CHARGER_STUNNED_DURATION 5 //TUNE
#define CHARGER_WALL_HURTBOX_THICKNESS 50
#define CHARGER_WALL_HURTBOX_DURATION 0.2

// TESLAS
#define TESLA_HEALTH 1
#define TESLA_RADIUS 12
#define TESLA_KNOCKBACK_COEFFECIENT 0
#define TESLA_STALKING_DURATION 6
#define TESLA_ATTACK_TELEGRAPH 1
#define TESLA_CHARGING_DURATION 5
#define TESLA_CHARGING_TELEGRAPH 1
#define TESLA_CHARGING_RADIUS_MULTIPLIER 2

// CIRCLES
#define FULL_RADIANS 2 * PI
#define LOWEST_ANGLE 1
#define HIGHEST_ANGLE 360

#endif